### ISSUE TITLE
Remove all ID attributes in design

### ISSUE THREAD

**Issue by Enelar** [Exsul/synchrotalk#11]
Only `id` tagged element allowed to use its `#canvas` on `body.ejs`. Everything else is bad practice, and should be abandoned. Phoxy stands against any absolute navigation.

Use class navigation instead. `name="thread-users"` is forbidden, `class="input on create thread user list"` is welcomed.

**Comment by macsanta** [comment]
Applayable

**Comment by Enelar** [comment]
??

**Comment by macsanta** [comment]
Sorry its means not applicable
