### ISSUE TITLE
Window.location alteration is unacceptable

### ISSUE THREAD

**Issue by Enelar** [Exsul/synchrotalk#14]
Phoxy has `reset` mechanism, equal to this hack. But it not welcomed, and usually should never be used. It breaks program execution and starts phoxy loading and warmup again. Clearing all variables and states. You probably want use `phoxy.MenuCall` for address change.

**Comment by macsanta** [comment]
Applayable

**Comment by Enelar** [comment]
?

**Comment by macsanta** [comment]
Sorry its means not applicable
